
import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { fetchTrendingNews } from '@/lib/news-service';
import { generateBlogPost } from '@/lib/ai-service';

// Initialize Supabase Admin Client
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
const isDryRun = !supabaseUrl || !supabaseServiceKey || supabaseUrl.includes('placeholder') || supabaseServiceKey === 'placeholder';

const supabase = !isDryRun ? createClient(supabaseUrl!, supabaseServiceKey!) : null;

export const dynamic = 'force-dynamic'; // Prevent caching
export const maxDuration = 300; // Allow running for up to 5 minutes (if hosted on Vercel Pro, otherwise might timeout)

export async function GET(req: NextRequest) {
    // 1. Security Check
    const authHeader = req.headers.get('authorization');
    const cronSecret = process.env.CRON_SECRET;

    if (authHeader !== `Bearer ${cronSecret}`) {
        // Also allow manual trigger if we are in development and simply don't have the header? 
        // No, strictly require secret to prevent abuse.
        // For manual testing, user can add the header.
        if (process.env.NODE_ENV === 'production' || cronSecret) {
            if (authHeader !== `Bearer ${cronSecret}`) {
                return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
            }
        }
    }

    try {
        // 2. Fetch News
        // Fetch slightly more than needed to account for duplicates/failures
        const articles = await fetchTrendingNews(15);

        if (articles.length === 0) {
            return NextResponse.json({ message: 'No news found' }, { status: 200 });
        }

        let createdCount = 0;
        const generatedPosts: any[] = [];
        const errors: any[] = [];
        const maxPosts = 5; // Target number of posts per run (requested by user)

        // 3. Process Articles
        for (const article of articles) {
            if (createdCount >= maxPosts) break;

            // Check if we already have a post about this (simple slug check will happen effectively during insert attempt or pre-check)
            // But we don't have the slug yet. 
            // Let's use the link or title to deduplicate if possible.
            // For now, we rely on the specific slug generated by AI.

            console.log(`Processing: ${article.title}`);

            // Generate Content
            const generatedPost = await generateBlogPost(article);

            if (!generatedPost) {
                errors.push({ title: article.title, error: 'Failed to generate content' });
                continue;
            }

            let existing = null;
            if (supabase) {
                const { data } = await supabase
                    .from('posts')
                    .select('id')
                    .eq('slug', generatedPost.slug)
                    .maybeSingle();
                existing = data;
            }

            if (existing) {
                console.log(`Skipping duplicate: ${generatedPost.slug}`);
                continue;
            }

            // 4. Generate Image (using Pollinations.ai for free AI images)
            // URL encode the title for the prompt
            const imagePrompt = encodeURIComponent(`${generatedPost.title} ${generatedPost.category_slug} minimal tech style`);
            const coverImageUrl = `https://image.pollinations.ai/prompt/${imagePrompt}?nologo=true&private=true&enhance=false`;

            // 5. Insert into DB (Skip if Dry Run)
            if (supabase) {
                const { error: insertError } = await supabase
                    .from('posts')
                    .insert({
                        title: generatedPost.title,
                        slug: generatedPost.slug,
                        excerpt: generatedPost.excerpt,
                        content_md: generatedPost.content_md,
                        cover_image_url: coverImageUrl,
                        tags: generatedPost.tags,
                        meta_title: generatedPost.meta_title,
                        meta_description: generatedPost.meta_description,
                        status: 'published', // Auto-publish!
                        category_id: null,
                        author: 'Curio AI Bot',
                    });

                if (insertError) {
                    console.error('Insert error:', insertError);
                    errors.push({ title: generatedPost.title, error: insertError.message });
                } else {
                    createdCount++;
                }

                // Try to update category_id based on slug
                if (generatedPost.category_slug) {
                    const { data: category } = await supabase
                        .from('categories')
                        .select('id')
                        .eq('slug', generatedPost.category_slug)
                        .single();

                    if (category) {
                        await supabase.from('posts').update({ category_id: category.id }).eq('slug', generatedPost.slug);
                    }
                }
            } else {
                createdCount++;
                (generatedPost as any).cover_image_url = coverImageUrl;
                (generatedPost as any).is_dry_run = true;
                generatedPosts.push(generatedPost);
            }
        }

        return NextResponse.json({
            success: true,
            is_dry_run: isDryRun,
            count: createdCount,
            results: isDryRun ? generatedPosts : undefined,
            errors: errors.length > 0 ? errors : undefined
        });

    } catch (error: any) {
        console.error('Cron job error:', error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
